Task: Feature Engineering

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
dataset = pd.read_csv("Dataset.csv")
dataset.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

Extract additional features from the existing columns, such as the length of the restaurant name or address.

In [2]:
dataset["Restaurant Name Length"]=dataset["Restaurant Name"].apply(lambda x:len(str(x)))
dataset["Address Length"]=dataset["Address"].apply(lambda x:len(str(x)))

In [3]:
dataset[["Restaurant Name","Restaurant Name Length","Address","Address Length"]]

,Restaurant Name,Restaurant Name Length,Address,Address Length
0,Le Petit Souffle,16,"Third Floor, Century City Mall, Kalayaan Avenu...",71
1,Izakaya Kikufuji,16,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...",67
2,Heat - Edsa Shangri-La,22,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...",56
3,Ooma,4,"Third Floor, Mega Fashion Hall, SM Megamall, O...",70
4,Sambo Kojin,11,"Third Floor, Mega Atrium, SM Megamall, Ortigas...",64
...,...,...,...,...
9546,NamlÛ± Gurme,11,"Kemankeï¿½ï¿½ Karamustafa Paï¿½ï¿½a Mahallesi, RÛ±htÛ±m ...",103
9547,Ceviz Aï¿½ï¿½acÛ±,12,"Koï¿½ï¿½uyolu Mahallesi, Muhittin ï¿½ï¿½stï¿½_ndaï¿½ï¿½ Cadd...",77
9548,Huqqa,5,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",73
9549,Aï¿½ï¿½ï¿½k Kahve,11,"Kuruï¿½_eï¿½ï¿½me Mahallesi, Muallim Naci Caddesi, N...",75
9550,Walter's Coffee Roastery,24,"Cafeaï¿½ï¿½a Mahallesi, BademaltÛ± Sokak, No 21/B, ...",65

Create new features like "Has Table Booking"or "Has Online Delivery" by encoding
categorical variables.

In [7]:
dataset["Has Table Booking"]=dataset["Has Table booking"].apply(lambda x:1 if x=="Yes"else 0)
dataset["Has Online Delivery"]=dataset["Has Online delivery"].apply(lambda x:1 if x=="Yes"else 0)

In [8]:
dataset[["Has Table booking","Has Table Booking","Has Online delivery","Has Online Delivery"]]

,Has Table booking,Has Table Booking,Has Online delivery,Has Online Delivery
0,Yes,1,No,0
1,Yes,1,No,0
2,Yes,1,No,0
3,No,0,No,0
4,Yes,1,No,0
...,...,...,...,...
9546,No,0,No,0
9547,No,0,No,0
9548,No,0,No,0
9549,No,0,No,0
9550,No,0,No,0